### ISSUE TITLE
add hint in find function

### ISSUE THREAD

**Issue by chy373** [art049/odmantic#149]
add hint in find function, so we can get result faster

another question: Why odmantic's model find function use motor's aggregate instead of find?

**Comment by art049** [comment]
Since there is not really the index support yet, it's probably not the best time to add this feature.
If you want to draft a PR, it wouldn't be a problem :grinning:

> Why odmantic's model find function use motor's aggregate instead of find?
The main benefit of using an agregation pipeline is to be able to get all the documents (even the referenced ones) in one single query.
