### ISSUE TITLE
Support MongoDB migration

### ISSUE THREAD

**Issue by ramzitannous** [art049/odmantic#61]
Allow migration to a new schema for mongodb

**Comment by erny** [comment]
I have implemented some naif migration system (currently only forward migrations) just creating a collection with the already executed migration steps and running the new ones. All migration steps are python scripts with name: `<date_time>_<number>_<description>` which are loaded with "exec" and have a "forward" function and a "backward" function and receive as first argument the database, e.g.:
```
async def forward(db):
    await db.registry_entry.update_many(
        {}, {
            "$rename": {
                "interesteds": "interested_list",
                "signers": "signer_list",
                "attachments": "attachment_list",
            }
        },
    )


async def backward(db):
    pass
```

This runs automatically on startup. To avoid double execution (with several worker processes) I use an exclusive file lock that allows just one process / thread to execute migrations (and index creation). 

So, perhaps, I would consider it out of scope. There are already migration systems for mongodb, both Python or MongoDB. You could also pipe scripts to mongoshell.

**Comment by art049** [comment]
Yes, this is a bit out of scope since Migration would typically give you access to the DB driver directly, and thus building migrations directly with ODMantic could be complicated (fetching multiple revisions of the same model).

In the meantime, you can use https://github.com/stxnext/pymongo-migrate or https://github.com/DoubleCiti/mongodb-migrations working both with pymongo.
