### ISSUE TITLE
custom id

### ISSUE THREAD

**Issue by fortunto2** [art049/odmantic#75]
Hi cool library.
I have a question, perhaps a stupid one.

How to make your own string values id?
I want nice to get such a tree structure.

https://docs.mongodb.com/manual/tutorial/model-tree-structures-with-parent-references/

```
db.categories.insertMany( [
   { _id: "MongoDB", parent: "Databases" },
   { _id: "dbm", parent: "Databases" },
   { _id: "Databases", parent: "Programming" },
   { _id: "Languages", parent: "Programming" },
   { _id: "Programming", parent: "Books" },
   { _id: "Books", parent: null }
] )

```

```
class Catalog(Model):
    id: str
    parent: Optional[str]


TypeError: can't automatically generate a primary field since an 'id' field already exists
```

**Comment by adeelsohailahmed** [comment]
Hi @fortunto2

Feel free to ignore if you already solved the issue, but I'm leaving the reference in case someone ends up here in the future.

By default, ODMantic generates an `id` field itself for every Model. [You can see the details here on why it does that.](https://art049.github.io/odmantic/fields/#the-id-field). This is the reason why you're getting an error, because ODMantic is trying generate an implicit `id` but it already exists (i.e. defined by you in the model).

To use the `id` field (or, really, any name for the field you want your primary field to be), you have to do this:

`from odmantic import AIOEngine, Field, Model

class Catalog(Model):
    id: str = Field(primary_field=True)
    parent: Optional[str] 
`

**Comment by fortunto2** [comment]
@adeelsohailahmed cool, thank you!
